Check if an Array is Sorted

In [ ]:
'''Input: arr[] = [20, 21, 45, 89, 89, 90]
Output: Yes

Input: arr[] = [20, 20, 45, 89, 89, 90]
Output: Yes

Input: arr[] = [20, 20, 78, 98, 99, 97]
Output: No

In [ ]:
def is_sorted(arr):
  for i in  range(1,len(arr)):
    if arr[i-1] >arr[i]:
      return False
  return True


arr=[20, 21, 45, 89, 89, 90]
is_sorted(arr)

True

Sort a Binary Array

In [ ]:

'''Input :  arr[] = [0, 1, 0, 1, 0, 0, 1, 1, 1, 0]
Output : arr[] = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]


Input :  arr[] = [1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1]
Output : arr[] = [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
arr = [0, 1, 0, 1, 0, 0, 1, 1, 1, 0]
zero=[]
one=[]
for i in range(len(arr)):
  if arr[i]==0:
    zero.append(arr[i])
  else:
    one.append(arr[i])
print(zero+one)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]


Move all zeros to end of array

In [ ]:
'''nput: arr[] = [1, 2, 0, 4, 3, 0, 5, 0]
Output: arr[] = [1, 2, 4, 3, 5, 0, 0, 0]
Explanation: There are three 0s that are moved to the end.


Input: arr[] = [10, 20, 30]
Output: arr[] = [10, 20, 30]
Explanation: No change in array as there are no 0s.


Input: arr[] = [0, 0]
Output: arr[] = [0, 0]
Explanation: No change in array as there are all 0s.

In [ ]:
arr = [1, 2, 0, 4, 3, 0, 5, 0]
zero=[]
# Create a new list with non-zero elements to avoid modifying the list being iterated.
non_zero_elements = []
for i in arr:
    if i != 0:
        non_zero_elements.append(i)
    else:
        zero.append(i)

# Concatenate the non-zero elements with the zeros.
result = non_zero_elements + zero
print(result)

[1, 2, 4, 3, 5, 0, 0, 0]


Separate Even and Odd Numbers

In [ ]:
'''Input: arr = [0, 1, 2, 3, 4]
Output: arr = [0, 2, 4, 1, 3]
Explanation: [0, 2, 4] are even and [1, 3] are odd numbers. Please note that [2, 0, 4, 3, 1] or [4, 2, 0, 1, 3] are also valid outputs. We only need to make sure that all even elements are before all odd.


Input : arr ={1, 5, 11}
Output : arr= {1, 5, 11}
Explanation All numbers are odd.'''

In [ ]:
 arr = [0, 1, 2, 3, 4]
 even=[]
 odd=[]
 for i in range(len(arr)):
  if arr[i]%2==0:
    even.append(i)
  else:
    odd.append(i)
print(even,odd)

[0, 2, 4] [1, 3]


In [ ]:
def separate_even_odd_in_place(arr):

    left = 0
    right = len(arr) - 1

    while left < right:
        while arr[left] % 2 == 0 and left < right:
            left += 1
        while arr[right] % 2 != 0 and left < right:
            right -= 1
        if left < right:
            arr[left], arr[right] = arr[right], arr[left]
            left += 1
            right -= 1

# Example usage:
arr = [0, 1, 2, 3, 4]
separate_even_odd_in_place(arr)
print(arr)  # Output: [0, 4, 2, 3, 1] (or a similar arrangement)

[0, 4, 2, 3, 1]


In [ ]:
'''nput: arr[] = [12, 11, -13, -5, 6, -7, 5, -3, -6]
Output: [-13, -5, -7, -3, -6, 12, 11, 6, 5]
Explanation: All negative elements [-13, -5, -7, -3, -6] were arranged before positive numbers [12, 11, 6, 5]. Note that there can be more than one possible output.


Input: arr[] = [11, -13, 6, -7, 5]
Output: [-13, -7, 11, 6, 5]
Explanation: All negative elements [-13, -7] were arranged before positive numbers [11, 6, 5].'''

In [ ]:
arr=[12, 11, -13, -5, 6, -7, 5, -3, -6]
pos=[]
neg=[]
for i in range(len(arr)):
  if arr[i]<0:
    neg.append(arr[i])
  else:
    pos.append(arr[i])
print(neg,pos)

[-13, -5, -7, -3, -6] [12, 11, 6, 5]


In [ ]:
arr = [12, 11, -13, -5, 6, -7, 5, -3, -6]
neg = [x for x in arr if x < 0]
pos = [x for x in arr if x >= 0]
print(neg, pos)

[-13, -5, -7, -3, -6] [12, 11, 6, 5]


In [ ]:
arr = [12, 11, -13, -5, 6, -7, 5, -3, -6]
neg = [x for x in arr if x %2== 0]
pos = [x for x in arr if x %2!= 0]
print(neg, pos)

[12, 6, -6] [11, -13, -5, -7, 5, -3]


Row wise sorting in 2D array

In [ ]:
'''Input :
77 11 22 3
11 89 1 12
32 11 56 7
11 22 44 33
Output :
3 11 22 77
1 11 12 89
7 11 32 56
11 22 33 44

Input :
8 6 4 5
3 5 2 1
9 7 4 2
7 8 9 5
Output :
4 5 6 8
1 2 3 5
2 4 7 9
5 7 8 9

In [ ]:
def matrix1(matrix):
    for i in range(len(matrix)):
        matrix[i].sort()
    return matrix




mat = [
    [77, 11, 22, 3],
    [11, 89, 1, 12],
    [32, 11, 56, 7],
    [11, 22, 44, 33]
]
print(matrix1(mat))


[[3, 11, 22, 77], [1, 11, 12, 89], [7, 11, 32, 56], [11, 22, 33, 44]]


In [ ]:
def row_wise_sort(matrix):
    for row in matrix:
        row.sort()
    return matrix

# Example usage:
matrix = [
    [77, 11, 22, 3],
    [11, 89, 1, 12],
    [32, 11, 56, 7],
    [11, 22, 44, 33]
]

sorted_matrix1 = row_wise_sort(matrix)
print(sorted_matrix1)

[[3, 11, 22, 77], [1, 11, 12, 89], [7, 11, 32, 56], [11, 22, 33, 44]]


In [ ]:
import numpy as np
def row_wise_sort(matrix1):
  matrix1=np.array(matrix1)
  sorted_matrix1=np.sort(matrix1,axis=1)
  return sorted_matrix1





matrix1 = [
    [77, 11, 22, 3],
    [11, 89, 1, 12],
    [32, 11, 56, 7],
    [11, 22, 44, 33]
]

sorted_matrix1 = row_wise_sort(matrix1)
print(sorted_matrix1)

[[ 3 11 22 77]
 [ 1 11 12 89]
 [ 7 11 32 56]
 [11 22 33 44]]


In [ ]:
import numpy as np

def print_matrix_numpy(lst, rows, cols):
    """Prints a list as a matrix using NumPy.

    Args:
        lst: The list to print as a matrix.
        rows: The number of rows in the matrix.
        cols: The number of columns in the matrix.
    """

    matrix = np.array(lst).reshape(rows, cols)
    print(matrix)

# Example usage
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print_matrix_numpy(my_list, 4, 3)  # Prints the list as a 3x4 matrix

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Python3 code to sort 2D matrix row-wise
def sortRowWise(m):

    # One by one sort individual rows.
    for i in range(len(m)):
        m[i].sort()

    # printing the sorted matrix
    for i in range(len(m)):
        for j in range(len(m[i])):
            print(m[i][j], end=" ")
        print()

    return 0

# Driver code
m = [[9, 8, 7, 1 ],[7, 3, 0, 2],[9, 5, 3, 2 ],[ 6, 3, 1, 2]]

sortRowWise(m)

# This code is contributed by shubhamsingh10


1 7 8 9 
0 2 3 7 
2 3 5 9 
1 2 3 6 


0

Sort the given matrix

In [ ]:
'''Input : mat[][] = { {5, 4, 7},
                       {1, 3, 8},
                       {2, 9, 6} }
Output : 1 2 3
         4 5 6
         7 8 9


Input: mat[][] = { {5, 4, 7},
                   {1, 3, 8} }
Output: 1 3 4
        5 7 8

In [ ]:
def sorted_mat(mat):
  for i in range(len(mat)):
    mat[i].sort()
  return mat

  for row in sorted_mat:

      for element in row:
       print(element, end=" ")
  print()


# Example usage:
mat1 = [[5, 4, 7], [1, 3, 8], [2, 9, 6]]
print(sorted_mat(mat1))

[[4, 5, 7], [1, 3, 8], [2, 6, 9]]


In [ ]:
def sorted_mat(mat1):
  matrix=np.array(mat1) # convert into numpy array
  sorted_matrix=np.sort(matrix.flatten(),axis=0).reshape(matrix.shape)
  return sorted_matrix

mat1 = [[5, 4, 7], [1, 3, 8], [2, 9, 6]]
print(sorted_mat(mat1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Python program for the above approach
# driver code
v = [[5,4,7], [1,3,8], [2,9,6]]
n = len(v)

x = []
for i in range(n):
    for j in range(n):
        x.append(v[i][j])

x.sort()
k = 0
for i in range(n):
    for j in range(n):
        v[i][j] = x[k]
        k += 1

print("Sorted Matrix will be: ")
for i in range(n):
    for j in range(n):
        print(v[i][j], end=" ")
    print("")

# THIS CODE IS CONTRIBUTED BY KIRTI AGARWAL(KIRTIAGARWAL23121999)


Sorted Matrix will be: 
1 2 3 
4 5 6 
7 8 9 


Sort an array in wave form


In [4]:
def wave_sort(arr):
  arr.sort()
  for i in range(0,len(arr),2):
    arr[i],arr[i+1]=arr[i+1],arr[i]
  return arr

arr = [10, 5, 6, 3, 2, 20, 100, 80]
print(wave_sort(arr))  #n log n

[3, 2, 6, 5, 20, 10, 100, 80]


In [6]:
def wave_sort_optimized(arr):

   for i in range(0,len(arr),2):
    if i>0 and arr[i]<arr[i-1]:
      arr[i],arr[i-1]=arr[i-1],arr[i-1]
    if i<0 and arr[i]>arr[i+1]:
      arr[i],arr[i+1]=arr[i+1],arr[i]
   return arr

# Example usage:
arr = [10, 5, 6, 3, 2, 20, 100, 80]
sorted_arr = wave_sort_optimized(arr)   #O(n)
print(sorted_arr)  # Output: [10, 5, 6, 2, 20, 3, 100, 80]

[10, 5, 6, 3, 3, 20, 100, 80]


Sort elements by frequency

In [ ]:
'''Input:  arr[] = {2, 5, 2, 8, 5, 6, 8, 8}
Output: arr[] = {8, 8, 8, 2, 2, 5, 5, 6}


Input: arr[] = {2, 5, 2, 6, -1, 9999999, 5, 8, 8, 8}
Output: arr[] = {8, 8, 8, 2, 2, 5, 5, 6, -1, 9999999}

In [ ]:
'''Input: arr[] = {2 5 2 8 5 6 8 8}

################approach_____________________________________________________________
Step1: Sort the array,
After sorting we get: 2 2 5 5 6 8 8 8
indexes:                    0 2 1 4 5 3 6 7



Step 2: Now construct the 2D array to maintain the count of every element as
Index, Count
0,      2
1,      2
5,      1
3,      3


Step 3: Sort the array by count (consider indexes in case of tie)
{{3, 3}, {0, 2}, {1, 2}, {5, 1}}
Print the elements using indexes in the above 2D array

In [13]:
def count_and_sort(arr):
    """
    Counts the occurrences of each element in an array, sorts the elements by count (and index if counts are equal), and prints the elements in a format where the value is the count.

    Args:
        arr: The input array of integers.

    Returns:
        None. Prints the sorted elements with their counts in the specified format.
    """

    counts = {}
    for num in arr:
        counts[num] = counts.get(num, 0) + 1

    # Sort the items in the dictionary by count, then by the element itself.
    sorted_counts = sorted(counts.items(), key=lambda item: (item[1], item[0]), reverse=True)

    # Print the elements and their counts in the desired format (value = times of key)
    result = []
    for element, count in sorted_counts:
        result.extend([element] * count)
    print(*result)  # Print elements in a space-separated format


# Example usage (with the input provided)
arr = [8, 8, 8, 2, 2, 5, 5, 6]
count_and_sort(arr)

8 8 8 5 5 2 2 6
